// Tolerance decay half-lives (in days), sourced from PsychonautWiki.
// This is a separate data module to keep analytics.ts focused on computation logic.

/** Tolerance half-lives keyed by lowercase substance identifier. */
export const TOLERANCE_HALF_LIVES_DAYS: Record<string, number> = {
  // ── Stimulants (dopaminergic) ──
  "2-aminoindane": 5,
  "2-fa": 5,
  "2-fma": 5,
  "3-fa": 5,
  "3-fpm": 5,
  "4f-eph": 5,
  "a-php": 5,
  "a-pvp": 5,
  adrafinil: 5,
  amphetamine: 5,
  armodafinil: 5,
  caffeine: 5,
  cocaine: 5,
  cyclazodone: 5,
  desoxypipradrol: 5,
  dichloropane: 3,
  "eth-cat": 2,
  ethylone: 5,
  ethylphenidate: 5,
  hexedrone: 5,
  isopropylphenidate: 5,
  kratom: 5,
  methamphetamine: 5,
  methiopropamine: 5,
  mexedrone: 5,
  modafinil: 5,
  "n-ethylhexedrone": 5,
  "n-methylbisfluoromodafinil": 5,
  nep: 5,
  "nm-2-ai": 5,
  oxiracetam: 5,
  pentedrone: 5,
  phenylpiracetam: 5,
  propylhexedrine: 5,
  theacrine: 5,
  tyrosine: 7,

  // ── Empathogens / Entactogens ──
  "2-fea": 5,
  "3-fea": 2,
  "3-fma": 5,
  "3-mmc": 5,
  "4-fa": 5,
  "4-fma": 5,
  "5-apb": 5,
  "5-mapb": 5,
  "6-apdb": 26,
  butylone: 5,
  mdai: 5,
  mdea: 38,
  mdma: 30,
  mephedrone: 5,
  methylone: 14,

  // ── Depressants (GABAergic) ──
  "1-4-butanediol": 5,
  "2m2b": 5,
  alcohol: 5,
  alprazolam: 5,
  baclofen: 5,
  clonazepam: 5,
  clonazolam: 5,
  deschloroetizolam: 5,
  diazepam: 5,
  diclazepam: 2,
  eszopiclone: 5,
  etizolam: 5,
  "f-phenibut": 5,
  flualprazolam: 5,
  flubromazepam: 5,
  flubromazolam: 5,
  flunitrazepam: 5,
  flunitrazolam: 5,
  gabapentin: 5,
  gbl: 5,
  ghb: 5,
  lorazepam: 5,
  methaqualone: 5,
  metizolam: 5,
  nicotine: 0.5,
  nifoxipam: 5,
  phenibut: 5,
  pregabalin: 5,
  pyrazolam: 5,
  temazepam: 5,
  zopiclone: 5,

  // ── Opioids (mu-receptor) ──
  acetylfentanyl: 5,
  codeine: 5,
  dextropropoxyphene: 5,
  dihydrocodeine: 5,
  ethylmorphine: 5,
  fentanyl: 5,
  heroin: 5,
  hydrocodone: 5,
  methadone: 5,
  "o-desmethyltramadol": 5,
  oxycodone: 5,
  pethidine: 5,
  tapentadol: 5,
  tramadol: 5,
  "u-47700": 5,

  // ── Dissociatives (NMDA antagonist) ──
  "2-fluorodeschloroketamine": 5,
  "3-ho-pce": 6,
  "3-ho-pcp": 6,
  "3-meo-pce": 5,
  "3-meo-pcmo": 5,
  "3-meo-pcp": 5,
  "4-meo-pcp": 5,
  deschloroketamine: 5,
  dextromethorphan: 5,
  diphenidine: 5,
  ephenidine: 5,
  hxe: 5,
  methoxetamine: 5,
  methoxphenidine: 5,
  mxipr: 5,
  nitrous: 5,
  "o-pce": 5,
  pce: 5,
  pcp: 5,

  // ── Cannabinoids (CB1) ──
  "5f-akb48": 5,
  "5f-pb-22": 5,
  "ab-fubinaca": 5,
  apica: 5,
  cannabis: 10,
  "jwh-018": 5,
  "jwh-073": 5,
  "thj-018": 5,
  "thj-2201": 5,

  // ── Hallucinogens (5-HT2A) ──
  "1b-lsd": 6,
  "1cp-al-lad": 6,
  "1cp-lsd": 6,
  "1cp-mipla": 6,
  "1p-eth-lad": 3,
  "1p-lsd": 6,
  "1v-lsd": 6,
  "2-5-dma": 4,
  "25b-nbome": 7,
  "25c-nboh": 7,
  "25c-nbome": 7,
  "25i-nboh": 7,
  "2c-b-fly": 3,
  "2c-d": 3,
  "2c-e": 2,
  "2c-i": 4,
  "2c-p": 3,
  "2c-t": 3,
  "2c-t-2": 3,
  "2c-t-21": 3,
  "2c-t-7": 3,
  "3c-e": 3,
  "3c-p": 3,
  "4-aco-det": 3,
  "4-aco-dipt": 3,
  "4-aco-dmt": 4,
  "4-aco-met": 3,
  "4-aco-mipt": 3,
  "4-ho-det": 3,
  "4-ho-dipt": 3,
  "4-ho-dpt": 3,
  "4-ho-ept": 3,
  "4-ho-met": 3,
  "4-ho-mipt": 3,
  "4-ho-mpt": 3,
  "5-meo-dalt": 3,
  "5-meo-dibf": 3,
  "5-meo-dipt": 3,
  "5-meo-dmt": 0.5,
  "5-meo-mipt": 3,
  "6-apb": 24,
  "al-lad": 6,
  "ald-52": 6,
  allylescaline: 3,
  bufotenin: 0.5,
  det: 3,
  dipt: 3,
  dob: 6,
  doc: 3,
  doi: 6,
  dom: 3,
  ept: 3,
  escaline: 3,
  "eth-lad": 6,
  lsa: 4,
  lsd: 4,
  "lsm-775": 6,
  lsz: 3,
  mda: 3,
  mescaline: 3,
  methallylescaline: 3,
  mipla: 6,
  mipt: 3,
  mpt: 3,
  "pargy-lad": 6,
  "pro-lad": 6,
  proscaline: 3,
  psilocin: 3,
  "psilocybin-mushrooms": 3,
  "tma-2": 3,
  "tma-6": 3,
  amt: 14,
  "bk-2c-b": 3,

  // ── Deliriants ──
  datura: 5,
  diphenhydramine: 5,
  mirtazapine: 3,

  // ── Nootropics ──
  "alpha-gpc": 7,
  aniracetam: 5,
  "choline-bitartrate": 7,
  coluracetam: 5,
  omberacetam: 5,
  piracetam: 5,
  pramiracetam: 5,
  "sam-e": 5,
  theanine: 5,
  tianeptine: 5,
}

/** Fallback half-life (in days) when substance is not in the table. */
export const DEFAULT_TOLERANCE_HALF_LIFE_DAYS = 5